name: C Action
author: Austen Stone
description: Calculate largest prime factor
branding:
  icon: "plus"
  color: "blue"

inputs:
  number:
    description: Number to find the largest prime factor of
    required: true

outputs:
  largest_prime_factor:
    description: The largest prime factor of the number

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number }}