name: Build & Test

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc -o main main.c
      - name: Archive main
        uses: actions/upload-artifact@v3
        with:
          name: main
          path: main