name: Usage

on:
  workflow_dispatch:
    inputs:
      number:
        default: "1000"
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  use:
    name: Get Largest Prime Factor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          number: ${{ inputs.number }}
        id: lpf
      - name: Log levels
        run: echo "::notice::The Largest Prime Factor is ${{ steps.lpf.outputs.largest-prime-factor }}."
