name: Usage

on:
  workflow_dispatch:
    inputs:
      number:
        default: "1000"
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    paths-ignore:
      - "**.md"

jobs:
  use:
    name: Get Largest Prime Factor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          number: ${{ inputs.number }}
        id: lpf
      - run: echo "The Largest Prime Factor is ${{ steps.lpf.outputs.largest-prime-factor }}."
      - run: echo "::notice The Largest Prime Factor is ${{ steps.lpf.outputs.largest-prime-factor }}."
      - name: Log levels
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::warning::This is a warning"
          echo "::error::This is an error"    

      - uses: actions/github-script@v5
        name: Print the response text
        with:
          script: core.notice('${{ steps.lpf.outputs.largest-prime-factor }})
